<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <url>https://github.com/jeap-admin-ch/jeap-reaction-observer/tree/main</url>
    <scm>
        <url>https://github.com/jeap-admin-ch/jeap-reaction-observer.git</url>
        <connection>scm:git:git://github.com/jeap-admin-ch/jeap-reaction-observer.git</connection>
        <developerConnection>scm:git:ssh://github.com:jeap-admin-ch/jeap-reaction-observer.git</developerConnection>
    </scm>
    <developers>
        <developer>
            <name>BIT</name>
            <email>jeap-community@bit.admin.ch</email>
            <organization>Federal Office of Information Technology, Systems and Telecommunication FOITT</organization>
            <organizationUrl>https://www.bit.admin.ch/</organizationUrl>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <artifactId>jeap-reaction-observer</artifactId>
    <name>${project.groupId}:${project.artifactId}</name>
    <version>6.8.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <artifactId>jeap-internal-spring-boot-parent</artifactId>
        <groupId>ch.admin.bit.jeap</groupId>
        <version>6.0.4</version>
    </parent>

    <properties>
        <maven.javadoc.skip>false</maven.javadoc.skip>
        <jeap-messaging.version>13.7.0</jeap-messaging.version>
        <commons-io.version>2.21.0</commons-io.version>
        <commons-beanutils.version>1.11.0</commons-beanutils.version>
    </properties>

    <modules>
        <module>jeap-reaction-observer-core</module>
        <module>jeap-reaction-observer-test</module>
        <module>jeap-reaction-observer-events</module>
        <module>jeap-reaction-observer-starter</module>
        <module>jeap-reaction-observer-messaging</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ch.admin.bit.jeap</groupId>
                <artifactId>jeap-reaction-observer-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.admin.bit.jeap</groupId>
                <artifactId>jeap-reaction-observer-events</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.admin.bit.jeap</groupId>
                <artifactId>jeap-reaction-observer-messaging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.admin.bit.jeap</groupId>
                <artifactId>jeap-reaction-observer-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.admin.bit.jeap</groupId>
                <artifactId>jeap-reaction-observer-test</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.admin.bit.jeap.messagetype.jeap</groupId>
                <artifactId>reaction-identified-event</artifactId>
                <version>2.0.0</version>
            </dependency>
            <dependency>
                <groupId>ch.admin.bit.jeap.messagetype.jeap</groupId>
                <artifactId>reactions-observed-event</artifactId>
                <version>1.0.0</version>
            </dependency>
            <!-- This is needed because commons-io 2.11.0  (CVE-2024-47554) is coming with spring-kafka-test 3.3.7 -->
            <!-- this is tracked by the jEAP team -->
            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons-io.version}</version>
            </dependency>
            <!-- This is needed because commons-beanutils 1.9.4 (CVE-2025-48734) is coming with spring-kafka-test 3.3.7 -->
            <!-- this is tracked by the jEAP team -->
            <dependency>
                <groupId>commons-beanutils</groupId>
                <artifactId>commons-beanutils</artifactId>
                <version>${commons-beanutils.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <!-- Check third-party license compliance -->
            <plugin>
                <groupId>org.honton.chas</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
            <!-- Generate third-party license list -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>license-maven-plugin</artifactId>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <configuration>
                        <archive>
                            <manifestEntries>
                                <Bundle-License>https://www.apache.org/licenses/LICENSE-2.0</Bundle-License>
                            </manifestEntries>
                        </archive>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>attach-javadocs</id>
                            <goals>
                                <goal>jar</goal>
                            </goals>
                            <configuration>
                                <doclint>none</doclint>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>

    </build>
</project>
